---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Homelab dashboard"
subtitle: "Quick access links"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: false
# footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.
footer: false

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
#message:
  #url: https://b4bz.io
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Demo !"
  icon: "fa fa-grin"
  content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Github"
    icon: "fab fa-github"
    url: "https://github.com/mroshan74"
    target: "_blank" # optional html a tag target attribute
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Proxmox"
        logo: "assets/tools/proxmox.png"
        subtitle: "Virtualization server"
        tag: "infra"
        # keywords: "server proxmox infra virtualization"
        url: "https://pve1.rtechie.com/"
        target: "_blank" # optional html a tag target attribute
      - name: "Portainer"
        logo: "assets/tools/portainer.png"
        subtitle: "Docker management"
        tag: "infra"
        url: "https://portainer.rtechie.com/"
        target: "_blank"
      - name: "Nginx Proxy Manager"
        logo: "assets/tools/npm.png"
        subtitle: "Reverse proxy manager"
        tag: "infra"
        url: "https://proxy.rtechie.com/"
        target: "_blank"
  - name: "Easy access"
    icon: "fas fa-solid fa-arrow-up-right-from-square"
    items:
      - name: "Cloudflare"
        logo: "assets/tools/cloudflare.png"
        subtitle: "Domain and DNS manager"
        tag: "cloud"
        url: "https://dash.cloudflare.com/9be36bae1a7635b9898d05c935a3bb7d"
        target: "_blank"
